In [2]:
 def convert_units(conversion_type, value):
    conversions = {
        "m_to_ft": value * 3.28084,
        "ft_to_m": value / 3.28084,
        "kg_to_lbs": value * 2.20462,
        "lbs_to_kg": value / 2.20462,
        "l_to_gal": value * 0.264172,
        "gal_to_l": value / 0.264172
    }

    if conversion_type in conversions:
        return conversions[conversion_type]
    else:
        raise ValueError("Unsupported conversion type.")

def unit_conversion_program():
    print("Select conversion type:")
    print("1. m_to_ft")
    print("2. ft_to_m")
    print("3. kg_to_lbs")
    print("4. lbs_to_kg")
    print("5. l_to_gal")
    print("6. gal_to_l")

    choice_map = {
        "1": "m_to_ft",
        "2": "ft_to_m",
        "3": "kg_to_lbs",
        "4": "lbs_to_kg",
        "5": "l_to_gal",
        "6": "gal_to_l"
    }

    try:
        choice = input("Enter choice (1-6): ")
        if choice not in choice_map:
            raise ValueError("Invalid choice.")

        value = float(input("Enter value to convert: "))
        result = convert_units(choice_map[choice], value)

        print(f"Converted value: {result}")

    except ValueError as e:
        print("Error:", e)

unit_conversion_program()

Select conversion type:
1. m_to_ft
2. ft_to_m
3. kg_to_lbs
4. lbs_to_kg
5. l_to_gal
6. gal_to_l
Enter choice (1-6): 2
Enter value to convert: 3
Converted value: 0.914399970739201


In [3]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return max(numbers)

def find_minimum(numbers):
    if len(numbers) == 0:
        raise ValueError("List is empty.")
    return min(numbers)

def math_operations_program():
    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Enter choice (1-4): ")
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("List cannot be empty.")

        if choice == "1":
            print("Result:", calculate_sum(numbers))
        elif choice == "2":
            print("Result:", calculate_average(numbers))
        elif choice == "3":
            print("Result:", find_maximum(numbers))
        elif choice == "4":
            print("Result:", find_minimum(numbers))
        else:
            print("Invalid choice.")

    except ValueError:
        print("Error: Please enter valid numeric input.")

math_operations_program()

Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 2
Enter numbers separated by spaces: 2
Result: 2.0


In [4]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[:n]

def get_last_n(lst, n):
    return lst[-n:]

def reverse_skip(lst):
    return lst[-2::-2]

data = [10, 21, 32, 43, 54, 65, 76, 87, 98, 109]

every_other = extract_every_other(data)
first_five = get_first_n(data, 5)
last_three = get_last_n(data, 3)
middle_part = remove_first_last(data)
sub = get_sublist(middle_part, 1, 4)
reversed_sub = reverse_list(sub)
weird_backward = reverse_skip(data)

print("Original:         ", data)
print("Every other:      ", every_other)
print("First 5:          ", first_five)
print("Last 3:           ", last_three)
print("Without first & last:", middle_part)
print("Sublist(1:4) from middle:", sub)
print("Reversed sublist: ", reversed_sub)
print("reverse_skip:     ", weird_backward)

Original:          [10, 21, 32, 43, 54, 65, 76, 87, 98, 109]
Every other:       [10, 32, 54, 76, 98]
First 5:           [10, 21, 32, 43, 54]
Last 3:            [87, 98, 109]
Without first & last: [21, 32, 43, 54, 65, 76, 87, 98]
Sublist(1:4) from middle: [32, 43, 54, 65]
Reversed sublist:  [65, 54, 43, 32]
reverse_skip:      [98, 76, 54, 32, 10]


In [5]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

def find_max(lst):
    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    flat_list = deep_flatten(lst)
    if len(flat_list) == 0:
        raise ValueError("List is empty.")
    return sum(flat_list) / len(flat_list)

nested = [1, 2, [3, 4, [5, 5, 6]], [7, [8, 9]], 10, [11, [12]], 5]

flat_one = flatten(nested)
print("flatten (one level):", flat_one)

val = access_nested_element(nested, [2, 2, 1])
print("access_nested_element([2,2,1]):", val)

total = sum_nested(nested)
print("sum_nested:", total)

cleaned = remove_element(nested, 5)
print("remove_element 5:", cleaned)

mx = find_max(nested)
print("find_max:", mx)

five_count = count_occurrences(nested, 5)
print("count_occurrences of 5:", five_count)

completely_flat = deep_flatten(nested)
print("deep_flatten:", completely_flat)

avg = average_nested(nested)
print("average_nested:", avg)

flatten (one level): [1, 2, 3, 4, [5, 5, 6], 7, [8, 9], 10, 11, [12], 5]
access_nested_element([2,2,1]): 5
sum_nested: 88
remove_element 5: [1, 2, [3, 4, [6]], [7, [8, 9]], 10, [11, [12]]]
find_max: 12
count_occurrences of 5: 3
deep_flatten: [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 5]
average_nested: 6.285714285714286


In [7]:
import numpy as np

In [8]:
# 1. Empty array 2x2
arr1 = np.empty((2,2))
print("Empty 2x2:\n", arr1)

# 2. All ones array 4x2
arr2 = np.ones((4,2))
print("\nOnes 4x2:\n", arr2)

# 3. Array filled with specific value
arr3 = np.full((3,3), 7)
print("\nFull array:\n", arr3)

# 4. Zeros like existing array
arr4 = np.zeros_like(arr3)
print("\nZeros like arr3:\n", arr4)

# 5. Ones like existing array
arr5 = np.ones_like(arr3)
print("\nOnes like arr3:\n", arr5)

# 6. Convert list to NumPy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nConverted list:\n", arr6)

Empty 2x2:
 [[3.98760182e-315 0.00000000e+000]
 [5.26400384e-091 2.43894035e-154]]

Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like arr3:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted list:
 [1 2 3 4]


In [9]:
# 1. Array from 10 to 49
arr = np.arange(10,50)
print("10 to 49:\n", arr)

# 2. 3x3 matrix 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n3x3 matrix:\n", matrix)

# 3. Identity matrix
identity = np.eye(3)
print("\nIdentity matrix:\n", identity)

# 4. Random array size 30 and mean
rand_arr = np.random.random(30)
print("\nMean:", rand_arr.mean())

# 5. 10x10 random min and max
rand_matrix = np.random.random((10,10))
print("\nMin:", rand_matrix.min())
print("Max:", rand_matrix.max())

# 6. Zero array size 10 and replace 5th element
z = np.zeros(10)
z[4] = 1
print("\nReplace 5th element:\n", z)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed:", arr[::-1])

# 8. 2D array with border 1 and inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder array:\n", border)

# 9. 8x8 checkerboard
checker = np.zeros((8,8))
checker[::2,1::2] = 1
checker[1::2,::2] = 1
print("\nCheckerboard:\n", checker)

10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.4829989590136998

Min: 0.0008239625725618982
Max: 0.9913187259387187

Replace 5th element:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [10]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("Addition:\n", x + y)

# 2. Subtract
print("Subtraction:\n", x - y)

# 3. Multiply by integer
print("Multiply by 3:\n", x * 3)

# 4. Square
print("Square:\n", x**2)

# 5. Dot products
print("v.w:", np.dot(v,w))
print("x.v:", np.dot(x,v))
print("x.y:\n", np.dot(x,y))

# 6. Concatenation
print("Concat rows:\n", np.concatenate((x,y), axis=0))
print("Concat columns:\n", np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1))

# 7. Concatenate x and v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)

# Explanation:
# Error occurs because x is 2D and v is 1D.
# Dimensions must match for concatenation.

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiply by 3:
 [[ 3  6]
 [ 9 15]]
Square:
 [[ 1  4]
 [ 9 25]]
v.w: 219
x.v: [29 77]
x.y:
 [[19 22]
 [50 58]]
Concat rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concat columns:
 [[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [11]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A_inv:\n", np.dot(A, A_inv))

# 2. Prove AB ≠ BA
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print("(AB)^T:\n", left)
print("B^T A^T:\n", right)

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [12]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using inverse:", X)

# Direct solve method (better method)
X2 = np.linalg.solve(A,B)
print("Solution using solve():", X2)

Solution using inverse: [ 2.  1. -2.]
Solution using solve(): [ 2.  1. -2.]


In [ ]:
import time

In [17]:
import time

size = 1000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [a + b for a,b in zip(list1,list2)]
print("Python list addition time:", time.time() - start)

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
print("NumPy addition time:", time.time() - start)

Python list addition time: 0.0001647472381591797
NumPy addition time: 0.0001232624053955078


In [18]:
start = time.time()
result = [a * b for a,b in zip(list1,list2)]
print("Python list multiplication time:", time.time() - start)

start = time.time()
result = arr1 * arr2
print("NumPy multiplication time:", time.time() - start)

Python list multiplication time: 0.00016736984252929688
NumPy multiplication time: 0.000152587890625


In [19]:
# Python
start = time.time()
dot = sum(a*b for a,b in zip(list1,list2))
print("Python dot product time:", time.time() - start)

# NumPy
start = time.time()
dot = np.dot(arr1,arr2)
print("NumPy dot product time:", time.time() - start)

Python dot product time: 0.00018477439880371094
NumPy dot product time: 0.00013446807861328125


In [21]:
size = 1000

# Python matrix multiplication
A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()
result = [[sum(A[i][k]*B[k][j] for k in range(size))
           for j in range(size)] for i in range(size)]
print("Python matrix multiplication time:", time.time() - start)

# NumPy matrix multiplication
A_np = np.ones((size,size))
B_np = np.ones((size,size))

start = time.time()
result = np.dot(A_np, B_np)
print("NumPy matrix multiplication time:", time.time() - start)

Python matrix multiplication time: 79.0873429775238
NumPy matrix multiplication time: 0.06306171417236328
